artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_file_path: E:\Projects\NLP_projects\Text_Classification(SPAM_Ham)word2vec\SMSSpamCollection.txt

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  data_dir : artifacts/data_ingestion/data.csv

data_transformation:
  root_dir: artifacts/data_transformtion
  data_path : artifacts/data_ingestion/data.csv
  final_model: artifacts/final_model
  preprocessor: artifacts/final_model/preprocessor.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  test_data: artifacts/data_transformtion/test.csv
  train_data: artifacts/data_transformtion/train.csv
  